/**
 * schemas.ts — Typed DTO interfaces mirroring the FastAPI backend response shapes.
 *
 * PURPOSE: Provides compile-time safety for all API responses. Instead of typing
 *   everything as `any`, these interfaces let TypeScript catch mismatches early.
 *
 * PATTERN: These are "Data Transfer Object" (DTO) types — they describe the shape
 *   of data moving between the backend and frontend. They mirror the Pydantic models
 *   in main.py.
 */

// ─── Upload ────────────────────────────────────────────────────────────────────
export interface UploadResponse {
  /** Server-side path where the file is stored (used for subsequent requests) */
  file_path: string;
}

// ─── Analyze Init ──────────────────────────────────────────────────────────────
export interface DatasetFingerprint {
  /** [rows, columns] */
  shape: [number, number];
  columns: string[];
  /** Column name → pandas dtype string (e.g. "object", "int64", "float64") */
  dtypes: Record<string, string>;
  /** Column name → % of null values (0–100) */
  null_pct: Record<string, number>;
  /** Column name → number of unique values */
  nunique: Record<string, number>;
  /** Column name → {min, max, mean, std} for numeric columns */
  numeric_stats?: Record<string, { min: number; max: number; mean: number; std: number }>;
  /** Up to 10 PII-redacted sample rows */
  safe_sample: Record<string, unknown>[];
}

export interface AnalyzeInitResponse {
  fingerprint: DatasetFingerprint;
  /** Short human-readable summary of the dataset (shape, column types, etc.) */
  safe_summary: string;
}

// ─── Diagnose ─────────────────────────────────────────────────────────────────
export interface DiagnoseResponse {
  /** Multi-line markdown health report generated by the AI */
  report: string;
  /** The OpenRouter model that actually generated this report */
  model_used: string;
}

// ─── Clean ────────────────────────────────────────────────────────────────────
export interface CleanAction {
  type: string;
  params?: Record<string, unknown>;
  stats?: { rows_before?: number; rows_after?: number; cols_affected?: number };
  order_index: number;
}

export interface CleanedDataInfo {
  /** Filename of the cleaned CSV (served from /api/downloads/{file_path}) */
  file_path: string;
  shape: [number, number];
  fingerprint: DatasetFingerprint;
  /** Auto-generated reproducible Python script content */
  python_code?: string;
}

export interface CleanResponse {
  message: string;
  /** Ordered list of actions that were executed (JSON) */
  plan: any;
  /** Conversational explanation from the AI */
  explanation: string;
  /** The actual Python code content */
  python_code: string;
  cleaned_data: CleanedDataInfo;
}

// ─── Metrics ──────────────────────────────────────────────────────────────────
export type MetricsTask = "classification" | "regression";

export interface ClassificationMetrics {
  task: "classification";
  accuracy: number;
  precision: number;
  recall: number;
  f1: number;
}

export interface RegressionMetrics {
  task: "regression";
  mae: number;
  mse: number;
  r2: number;
}

export type MetricsResponse = ClassificationMetrics | RegressionMetrics;

// ─── Chat ─────────────────────────────────────────────────────────────────────
export interface ChatResponse {
  reply: string;
}

// ─── Role / Onboarding ────────────────────────────────────────────────────────
export type UserRole = "beginner" | "intermediate" | "senior";
export type UserPurpose = "chat" | "diagnosis" | "cleaning";

export interface UserPreferences {
  role: UserRole;
  purpose: UserPurpose;
}
